CREATE DATABASE GESTION_PACKAGES;

USE GESTION_PACKAGES ;

CREATE TABLE PACKAGES (
   ID_PACK  INT PRIMARY KEY AUTO_INCREMENT,
    NOM  CHAR(10) NOT NULL,
    DESCRPITION CHAR(200) NOT NULL  
)

CREATE TABLE AUTEUR (
  ID_AUTEUR INT PRIMARY KEY AUTO_INCREMENT,
  NOM_AUTEUR VARCHAR(16),
  EMAIL VARCHAR(255) NOT NULL UNIQUE

)
